---
# tasks file for epel

- name: Include OS major ver vars file
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- name: Ensure EPEL is installed
  shell: rpm -q epel-release || yum install -y {{ epel_rpm }}

