---
# tasks file for packages

- name: Ensure basic packages are installed
  yum: name={{ item }} state=present
  with_items: packages
  when: packages is defined

- name: Ensure python-pip packages are installed
  pip: name={{ item }} state=present
  with_items: packages_pip
  when: packages_pip is defined
