---
dependencies: []

galaxy_info:
  author: geerlingguy
  description: Java for RHEL/CentOS 6.x and Debian/Ubuntu
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 1.4
  platforms:
  - name: EL
    versions:
    - 6
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  categories:
    - development
    - system
    - web
