---
# install jenkins

- hosts: all:!tag_type_tower
  gather_facts: true
  user: ec2-user
  sudo: true

  tasks:
    - name: Dynamic grouping
      group_by: key={{ ec2_tag_env }}_{{ ec2_tag_type }}
      tags: [ prod_web, prod_db, prod_jenkins ]

- hosts: prod_jenkins
  sudo: yes
  roles:
    - { role: geerlingguy.java }
    - { role: geerlingguy.jenkins }
