---
# vim: set ft=ansible:
- hosts: localhost
  gather_facts: false
  connection: local

  vars:
    region:   eu-west-1
    ami:      ami-9d23aeea # Amazon Linux 2014.09.2
    # nat instance: ami-14913f63
    keypair:  mphillips
    set_dns:  False
    count:    1
    tags:
      env:  "{{ tags_env  | default('prod') }}"
      type: "{{ tags_type | default('web') }}"
    wait_for_ssh: False

  tasks:
    - name: Check for variables
      fail: msg="Must supply vpc_subnet to -e"
      when: vpc_subnet is not defined

    - name: Launch instance
      local_action:
        module: ec2
        keypair: "{{ keypair }}"
        instance_type: "{{ type | default('t2.medium') }}"
        vpc_subnet_id: "subnet-{{ vpc_subnet | default('459a9231') }}"
        image: "{{ ami }}"
        region: "{{ region }}"
        count: "{{ count }}"
        wait: yes
        instance_tags: "{{ tags }}"
        user_data: "{{ lookup('file', '../../scripts/ec2_bootstrap.sh') }}"
        assign_public_ip: "{{ assign_eip | default(true) }}"
      register: ec2

    - name: Ensure new instances can access Tower
      ec2_group:
        name: default
        description: "default VPC security group"
        region: "{{ region }}"
        vpc_id: vpc-ec5e458e
        purge_rules: false
        rules:
          - proto: all
            from_port: 0
            to_port: 65535
            cidr_ip: "{{ item.public_ip }}/32"
      with_items: ec2.instances

    - name: Instance info
      debug: msg="{{ item.id }} {{ item.public_ip }}"
      with_items: ec2.instances

