---
# vars for web servers

packages:
  - git
  - telnet

app_repo: https://github.com/phips/flask_app.git
app_branch: tiad
app_cow: tiad
app_clone: true
app_pips:
  - Flask
  - Flask-Bootstrap

nginx_sites:
  - server:
      file_name: hello
      listen: 80
      server_name: "{{ inventory_hostname }} www.bovine.cow bovine.cow localhost"
      root: "/srv/www/html"
      location1: { name: /, try_files: "$uri $uri/ /index.html" }

elb_reg: False
