---
# tasks file for yum
# vim: set ft=ansible:

- name: Ensure fastestmirror is disabled
  lineinfile: dest=/etc/yum/pluginconf.d/fastestmirror.conf
              regexp='^enabled=' line='enabled=0'
              state=present
  when: ansible_distribution == 'CentOS'

- name: Enable extra Yum repositories
  template: src=template.repo.j2 dest=/etc/yum.repos.d/{{ item.label }}.repo
            owner=root group=root mode=0644
  when: yum_repos is defined
  with_items: yum_repos
  
